DEFAULT_WEIGHT_SQFLUX                  = 1
DEFAULT_WEIGHT_NONQS                   = 1
DEFAULT_WEIGHT_BRES                    = 1e3
DEFAULT_WEIGHT_IOTA                    = 1e4
DEFAULT_WEIGHT_COIL_LENGTH             = 5e-2
DEFAULT_WEIGHT_COIL_CURVATURE          = 1e-2
DEFAULT_WEIGHT_COIL_COIL_DISTANCE      = 1e6
DEFAULT_WEIGHT_COIL_SURFACE_DISTANCE   = 1e2

DEFAULT_MAX_POLOIDAL_EXTENT            = 70.00 # degrees
DEFAULT_MAX_ELLIPSE_WIDTH              = 0.197 # meters
DEFAULT_MIN_ELLIPSE_WIDTH              = 0.050 # meters
DEFAULT_MIN_GLOBAL_CURVATURE_RADIUS    = 0.010 # meters
DEFAULT_GCR_EXP_WEIGHT                 = 0.010 # meters
DEFAULT_WEIGHT_POLOIDAL_EXTENT         = 1e2
DEFAULT_WEIGHT_ELLIPSE_WIDTH           = 1e1
DEFAULT_WEIGHT_GLOBAL_CURVATURE_RADIUS = 1e3
DEFAULT_WEIGHT_CURRENTS                = 1e6
